### PR TITLE
Correct naming

### PR DESCRIPTION
**Pull request by hythloda**

### CODE REVIEW

**Comment by stewartbryson** [comment]
Is Gradle no longer an Apache project?

**Comment by stewartbryson** [comment]
The `src/markdown/README.md` file is actually the source for the README. There's a process that replaces current version number, etc. I made the change and pushed myself, so closing this PR and not merging.

**Comment by hythloda** [comment]
Thanks a ton! I wanted to potentially list this plugin in the next [newsletter](https://newsletter.gradle.com/) just needed it to have the right name in the README

**Comment by stewartbryson** [comment]
That would be awesome! Anything I can do to remove that “potentially” tag? ;-)

Stewart Bryson
770-823-7409

**Pull request closed without merging**
